### ISSUE TITLE
Add support for custom generated files (static assets)

### ISSUE THREAD

**Issue by ackvf** [luni64/VisualTeensy#18]
Now that I am going through the Teensy tutorial, it is apparent that I will always have a need to copy certain files to each new project, such as `.editorconfig` and `.gitignore`.

I can think of two solutions:

**A) Easier** - Introduce a folder within VisualTeensy called `assets` which will hold custom static assets that will always be copied to new project. Perhaps if a folder structure is introduced, the files would be merged to the respective folders in the new project.

**B)** Add an inapp editor which could reuse existing elements to set the _file content_ and configure _path_
![image](https://user-images.githubusercontent.com/2313018/74362193-8b0e7580-4dc8-11ea-9575-1fadef99a014.png)

_PS: When I thought about the option B, I was under the assumption that the Generated Files text area is editable._

**Comment by luni64** [comment]
Thats a **very** good idea. I find myself copying .clang-format to the projects. I'll implement something like that in the next version

**Comment by luni64** [comment]
Added a wish list to the issues (see #19)
