### ISSUE TITLE
New library manager

### ISSUE THREAD

**Issue by luni64** [luni64/VisualTeensy#2]
Here V0.6 which should fix the library issue. [VisualTeensy.zip]
[VisualTeensy_v0.61.zip](https://github.com/luni64/VisualTeensy/files/2425252/VisualTeensy_v0.61.zip)

Any tests welcome

**Comment by WMXZ-EU** [comment]
copied VisualTeensy.zip but VisualTeensy. exe does not start (or crashes)
(maybe wrong net library)
is in develop latest code?

**Comment by WMXZ-EU** [comment]
can you re-post the mods for the LIB_OBJ for 'old library structure'
I cannot find the code anymore

**Comment by luni64** [comment]
> getLibs(@"C:\Arduino\arduino-1.8.7\hardware\teensy\avr\libraries"); or similar
> replaced string by 'libPath'

Sorry, was working on the Library manager already..  I'll exchange the exe. ... and I'll wrap the app in a try catch block to get more information if it crashes :-/  

> can you re-post the mods for the LIB_OBJ for 'old library structure'
> I cannot find the code anymore

Sorry, don't understand your  request. If you need the current makefile "tail" you find it here `https://github.com/luni64/VisualTeensy/blob/develop/VisualTeensy/Embedded/makefile` 

Yes, latest code is in develop

**Comment by luni64** [comment]
Just had a look but I didn't check that version in. Anyway, I didn't change much

![image](https://user-images.githubusercontent.com/12611497/46164074-447cb180-c28d-11e8-9e5f-1faf8ed6e1f8.png)

If you remove the marked part (without the last closing bracket)  the /utility subdir is not included and you can add it manually. I don't think I changed anything else regarding the libs. 
Second line handles the src folder you can comment that out completely if you don't want it.

**Comment by luni64** [comment]
Updated the zip in fist post
