### ISSUE TITLE
Upload via teensy.exe doesn't work

### ISSUE THREAD

**Issue by jonbro** [luni64/VisualTeensy#24]
When uploading via teensy.exe, I get the following failure:
`Teensy Loader could not find the file teensyPlaits`
this is the result of running the command:
`C:\Users\jonbro\Documents\teensyPlaits>"C:\PROGRA~2\Arduino\hardware\tools/teensy_post_compile" -test -file=teensyPlaits -path=".vsteensy\build" -tools="C:\PROGRA~2\Arduino\hardware\tools" -board=TEENSY40 -reboot`
It seems like the issue is that teensy_post_compile requires the full path, so switching the command to the following works
`C:\Users\jonbro\Documents\teensyPlaits>"C:\PROGRA~2\Arduino\hardware\tools/teensy_post_compile" -test -file=teensyPlaits -path="C:\Users\jonbro\Documents\teensyPlaits\.vsteensy\build" -tools="C:\PROGRA~2\Arduino\hardware\tools" -board=TEENSY40 -reboot`

**Comment by luni64** [comment]
This is strange, works here. Can you provide some context? Versions of Arduino/Teensyduino and VisualTeensy?
