### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by Vission01** [luni64/VisualTeensy#25]
Clean PC, new install of VSCode, installed c/c++ extension.  downloaded VisualTeensy v0.9.7.3 started VisualTeensy.exe.  Windows asks for Arduino folder or leave empty.  I leave empty and click Start VisualTeensy, get the error attached.  (Win10 Pro x64 v1909)

![Capture](https://user-images.githubusercontent.com/9039312/82826976-1396ba80-9e7c-11ea-9f20-df174cc2ff60.PNG)

Please advise.

**Comment by luni64** [comment]
Can you try to enter the Arduino folder?

**Comment by Vission01** [comment]
Had not installed arduino at all.  I found that after installing Arduino it now works even without choosing a folder.


-------- Original message --------

**Comment by luni64** [comment]
Great, hope it works stable now for you
