### ISSUE TITLE
VisualTeensy does not start

### ISSUE THREAD

**Issue by Huebenthal** [luni64/VisualTeensy#26]
After entering the Arduino folder (or even leave it empty) I just get a fault report that some object link does not point on a object instance (see attached screen shot).
![Unbenannt](https://user-images.githubusercontent.com/2990610/83135212-cd449400-a0e5-11ea-9bb4-bcb13f72afc7.png)
OS: Windows 10 64bit

**Comment by luni64** [comment]
This is very strange, is this on first startup when it asks you to enter an Arduino Folder?

**Comment by Huebenthal** [comment]
It appears when I press "Start VisualTeensy" on the first screen where the path to Arduino is set up. Brand new installation.

**Comment by luni64** [comment]
Sorry for my late answer, I was traveling yesterday...

It is always difficult to debug things which only appear on fresh installations...  I suspect that some of the required files will be generated by Arduino after a first use. So my suggestions would be to try to compile and upload a simple blink.ino with the Arduino IDE first and try if you can start VisualTeensy afterwards.

**Comment by Huebenthal** [comment]
No change. I re-installed Arduino and the Teensy extension but no change either. I'll stay with the Teensy development in the Arduino IDE.

**Comment by luni64** [comment]
Using it for daily work on various PCs without issues. Works for others as well.  
Best wishes
