### ISSUE TITLE
After following the getting started can't find SPI.h

### ISSUE THREAD

**Issue by s4lt3d** [luni64/VisualTeensy#27]
I'm using teensy 4.1 with all the latest things. I can program it just fine in the arduino ide, after following your build example video it works. Putting <SPI.h> at the top of the code it gives error about not finding SPI.h. Any help would be great.

**Comment by luni64** [comment]
I need more information to really help you. Did you add the SPI library to VisualTeensy?

**Comment by s4lt3d** [comment]
Thanks! I hadn't realized that SPI was an extra library since it just comes with normal arduino. I found and included it. That fixed my issue. Thanks for the quick reply!!
