### ISSUE TITLE
Sort the library versions by number

### ISSUE THREAD

**Issue by mechatroniks-git** [luni64/VisualTeensy#42]
I had been running this particular library at v2.9.2 as I just picked the last one on the list, but just realized the newest version (2.28.10) is higher than the last. 

Nice to have it sorted properly, with the latest at the bottom. 

![image](https://user-images.githubusercontent.com/57600622/114248214-f364d280-994b-11eb-90d4-44fad3c72a7d.png)

**Comment by luni64** [comment]
Thanks for spotting this. Should be fixed in v0.9.9.3. Can you give it a try?

**Comment by mechatroniks-git** [comment]
Just had a chance to check it out, looks good to me. Thanks.
