### ISSUE TITLE
Exception when source libraries are on different drive than project

### ISSUE THREAD

**Issue by benpeart** [luni64/VisualTeensy#43]
I have my Arduino install on drive C but my project is on drive D. 

![2021-04-17 (1)](https://user-images.githubusercontent.com/15252029/115131750-66172300-9fc8-11eb-9176-62bf59e1ccbc.png)

When I used the library manager to move a library from the Arduino Repository to my project, I get an exception.

![2021-04-17](https://user-images.githubusercontent.com/15252029/115131705-2f410d00-9fc8-11eb-98c4-acce28d8a21c.png)

**Comment by luni64** [comment]
Fixed in v0.9.9.3. Can you give this a try?

**Comment by benpeart** [comment]
That was quick! I tried it again with 0.9.9.3 and it worked correctly this time. Thanks.
