### ISSUE TITLE
Unable to upload image using teensy.exe build task

### ISSUE THREAD

**Issue by benpeart** [luni64/VisualTeensy#46]
When I use the "Upload (teensy.exe) build task, I get the following error:

```
> Executing task: & 'C:/Program Files/VisualTeensy/make.exe' upload -j -Otarget <

Teensy Loader could not find the file HelloBlinkingWorld
quitmake: *** [makefile:164: upload] Error 1
The terminal process "C:\Program Files\PowerShell\7\pwsh.exe -Command & 'C:/Program Files/VisualTeensy/make.exe' upload -j -Otarget" terminated with exit code: 1.
```

I have been unable to figure out why it is unable to find my binary (HelloBlinkingWorld in this case). The tycommander build task uploads fine in this same project. I've created several different projects trying to figure out why it is failing but without success.

![2021-04-20 (2)](https://user-images.githubusercontent.com/15252029/115455933-93deb080-a1f0-11eb-93fe-0483ef4419c1.png)

**Comment by luni64** [comment]
Interesting, I can have a closer look if you post the following files: 

.vsteensy/vsteensy.json
.vscode/c_cpp_properties.json
and the generated makefile

**Comment by luni64** [comment]
I'm wondering why it uses the powershell instead of the usual cmd.exe to execute make.  Did you apply a special Windows setting for this?

**Comment by dontfeedthenerd** [comment]
I have the same problem both with TYcommander and the PJRC.
I have attached my files


[c_cpp_properties.zip](https://github.com/luni64/VisualTeensy/files/6354320/c_cpp_properties.zip)

**Comment by luni64** [comment]
Unfortunately I can't reproduce this here. Your files look perfectly normal.  Can you please open the makefile and remove the @ in lines 164 and 165:

![image](https://user-images.githubusercontent.com/12611497/115655284-461e9100-a333-11eb-9e22-2653244e8dd0.png)

You then should see the actual command issued when it tries to upload the file. Check if the path and filename correspond to the location of your hex image.  You can also copy the line into a new vscode terminal and  execute it manually. Screenshots of those experiments would be helpful.

**Comment by dontfeedthenerd** [comment]
![image](https://user-images.githubusercontent.com/679650/115754331-f222a500-a350-11eb-9543-d6adce337b71.png)
Looks like the .hex isn't being appended to the -file?

**Comment by dontfeedthenerd** [comment]
Nope that's not it... hmmm. I think it may need the full path to-file?

**Comment by luni64** [comment]
Just to make sure: Your project is called teensyproj and you find the file `teensyproj.hex` in  the `vsteensy/build` folder, right? 
Did you try to manually call the command from a vscode terminal? Does it work then?

**Comment by dontfeedthenerd** [comment]
That is correct I can find a teensyproj.hex
As a matter of fact I've been using VisualTeensy to build then manually
loading using the teensyloader.

**Comment by luni64** [comment]
>As a matter of fact I've been using VisualTeensy to build then manually
yes but did you try exactly the command which is shown in your screenshot? 

This works here since years without issue. Very weird. What is the output of a call to TyCommander?

**Comment by dontfeedthenerd** [comment]
![image](https://user-images.githubusercontent.com/679650/115765897-28b1ed00-a35c-11eb-9246-8f1478cf0379.png)
This is the output to TyCommander let me try running it manually

**Comment by dontfeedthenerd** [comment]
![image](https://user-images.githubusercontent.com/679650/115766211-93632880-a35c-11eb-94bd-026b7fe765e0.png)

This is the output while running manually

**Comment by dontfeedthenerd** [comment]
did it in a command prompt running as admin same issue and here's proof the .hex exists:
![image](https://user-images.githubusercontent.com/679650/115766768-30be5c80-a35d-11eb-95ad-3b4acc272120.png)

**Comment by dontfeedthenerd** [comment]
Thank you for your help!

This is the result of that:
![image](https://user-images.githubusercontent.com/679650/115767327-dd004300-a35d-11eb-9743-87eb1cc0a5e5.png)


It just hangs I have to ctrl+C out of it

**Comment by dontfeedthenerd** [comment]
oh wait here we go:
![image](https://user-images.githubusercontent.com/679650/115768186-d6be9680-a35e-11eb-88ba-1fca3bbc9e7e.png)

**Comment by luni64** [comment]
Ok, now I can reproduce it. You obviously removed the "" around the command otherwise powershell reports an errror right? If I do the same I get the file not found issue. Looks like this only happens if vscode uses the powershell terminal. Can you switch to a cmd terminal and try if it works then? 

open the terminal combobox and select "Select Default Profile" 
![image](https://user-images.githubusercontent.com/12611497/115773120-37c28a80-a3b0-11eb-97df-3be1d9d6d400.png)

Select "Command Prompt" (instead of the currently selected PowerShell) 

![image](https://user-images.githubusercontent.com/12611497/115773632-d5b65500-a3b0-11eb-8c83-e07d9eb5a3cd.png)

Close all open termials:
![image](https://user-images.githubusercontent.com/12611497/115773781-fd0d2200-a3b0-11eb-8ca3-8a61d6437e99.png)

and try to upload....

**Comment by dontfeedthenerd** [comment]
No Joy :(

![image](https://user-images.githubusercontent.com/679650/115774208-22c10980-a366-11eb-9c0e-76083f80dcad.png)

**Comment by dontfeedthenerd** [comment]
![image](https://user-images.githubusercontent.com/679650/115774285-3e2c1480-a366-11eb-8c28-343281df7daa.png)
tried running the command manually

**Comment by luni64** [comment]
does it even find the file if you do
type .vsteensy\build\teensyproj  in the vscode terminal?

**Comment by dontfeedthenerd** [comment]
it does
![image](https://user-images.githubusercontent.com/679650/115775954-66b50e00-a368-11eb-823d-0e514c81bda7.png)

**Comment by luni64** [comment]
Sorry, need to sleep over it. Maybe something changed in the call parameters of the teensy uploader. Can you check what your Arduino installation spits out to upload the hex (need to switch to verbose output to see it).

**Comment by dontfeedthenerd** [comment]
Yeah take your time, I don't mind using teensy to upload

**Comment by benpeart** [comment]
Switching to "Command Prompt" as the default terminal window got the teensy uploader working for me. Would be nice if it worked in powershell as well but at least I have a good workaround. Thank you!

**Comment by lnductor** [comment]
For anyone else searching this in the future: I had the same error message but a different root cause. Turns out I just needed to close the teensy.exe loader window opened by the Arduino app.
