### ISSUE TITLE
 Visual Teensy 1.0.0.0 wrong window title

### ISSUE THREAD

**Issue by leadermik** [luni64/VisualTeensy#52]
Many thanks for your amazing software!

Maybe a trivial issue here. 

Just downloaded the .zip of the Visual Teensy 1.0.0.0 release, yet the version on the window title does not match 😅. 

![Capture](https://user-images.githubusercontent.com/7304125/123085768-ecb20b80-d422-11eb-87bc-a1121905df5b.PNG)

**Comment by luni64** [comment]
Thanks for spotting this. It is already fixed in the current code. I didn't generate a binary release so far since I want to fix another small issue first.

**Comment by luni64** [comment]
fixed in v1.2.0
