### ISSUE TITLE
`Copy local core` and `Clone core from gitHub` incorrectly sets core includePath

### ISSUE THREAD

**Issue by Michael2MacDonald** [luni64/VisualTeensy#59]
"Copy local core into project" and "Clone core from gitHub into project" incorrectly sets the `c_cpp_properties.json` `includePath` for cores to `C:/Program Files (x86)/Arduino/hardware/teensy/avr/cores/teensy4` when it should be setting it to `core/teensy4`.

This is less of an issue for `Copy local core into project` because the makefile still points to `core/teensy4` for compiling (Which is important if you modified the core, like increasing the serial buffer for example).

But, for `Clone core from gitHub into project` this will lead to VSCode giving include errors if you don't have the Arduino IDE and Teensyduino installed.

**Comment by luni64** [comment]
Thanks for spotting this. Should be fixed in 1.3.0 beta1 https://github.com/luni64/VisualTeensy/releases/tag/v1.3.0_beta1
Let me know if it works for you
