### ISSUE TITLE
Clone core from github into project should not bring in .git & .github folders

### ISSUE THREAD

**Issue by mechatroniks-git** [luni64/VisualTeensy#67]
I have to delete the .git and .github folders after cloning, so github desktop will commit my stuff. Otherwise, I get the error shown below.  For v1.4.0

I also delete the .gitignore. Perhaps keywords.txt and readme.md should stay?

![image](https://user-images.githubusercontent.com/57600622/143403948-b3437398-153b-4c4b-b7c6-1171ef5e24a0.png)

**Comment by luni64** [comment]
Can you give me a more complete description on how I can reproduce the issue?

**Comment by mechatroniks-git** [comment]
Here are my steps, thanks for looking at this.

1. I create a blank project in v1.4.0 Visualteensy
2. I select "clone core from Github into project"
3. Save project
4. Project opens in VSCode
5. Then I go into Github Desktop to publish the project, it gives me the above error.
6. By deleting the git folders inside the Cores directory, Github Desktop allows me to publish the repo

I compared other projects I had (using visualteensy 1.2.0 & "clone local core into project" and noticed these extra files/folders.

**Comment by luni64** [comment]
Thanks,  I'll have a look why Github Desktop stumbles over it. 
Anyway, the '.git  folder' is the whole point of cloning the library. Deleting it renders the clone to a simply snapshot copy. Looks like you want to select Copy instead of clone? 

![image](https://user-images.githubusercontent.com/12611497/143542261-9d889ca5-a097-469f-b4a0-41bb37a80909.png)

**Comment by luni64** [comment]
The following applies if you really want to **clone** the core files into your project. If you want to **copy** them do as mentioned above. 

----

I did a few experiments and can reproduce the issue you have with GitHub Desktop. If you clone the core libraries into a project which you want to upload to gitHub (or any other git server) later, you need to tell your project that it should treat the cloned cores folder as a git submodule. Unfortunately the git library I use can't currently do this automatically so there is a small manual step required: 

1) Clone the core files into the project with VisualTeensy. This will first git-init your project and then add the Teensy core as git repository to it. 

![image](https://user-images.githubusercontent.com/12611497/143578248-9e65ffbe-ef6b-4d28-9f99-fe3f156cbf0a.png)

2) In VSC, open a terminal and type `git submodule add https://github.com/paulstoffregen/cores ./cores` this will 'register' the cloned core library as submodule to the main repo

![image](https://user-images.githubusercontent.com/12611497/143579612-edab5a8c-770a-4214-a2f2-2a7987ad572d.png)

3) In Github Desktop choose File | Add local Repository and browse to your project folder. Don't forget to commit

![image](https://user-images.githubusercontent.com/12611497/143580013-8c45b867-265d-4581-a34b-2532d0b16325.png)

Then, use the publish repository button to generate the repo in GitHub.  In Github you will see that the cores folder is empty. Actually it simply links to the location it was cloned from originally. I.e. github.com/paulstoffregen/cores . When you clone your repo from Github it automatically grabs the core files from there
![image](https://user-images.githubusercontent.com/12611497/143581122-c8980b25-7476-4bdf-b378-f201eb25046f.png)

Hope that helps
