### ISSUE TITLE
how to edit libraries

### ISSUE THREAD

**Issue by finncat62** [luni64/VisualTeensy#73]
Hi Luni, it's me again(sorry)

This one should be super simple and fast.
context:
I'm using a library that replaces another (teensy4_i2c instead of wire), but some libraries depend on wire. Luckily, the creator of i2c said that I just have to go to the libraries and replace references to wire to the new library. 

question:
the way that visual studio code starts puts all the teensyduino and arduino libraries in the lib folder, but I don't know where the others are?  Is there a way I can edit them for just inside this project, leaving them the same for all other projects that include those libraries?

![image](https://user-images.githubusercontent.com/47909923/177019062-4df045f5-74f8-4ec7-8dab-d5ce37f4ef04.png)

![image](https://user-images.githubusercontent.com/47909923/177019073-86bec603-80dc-470e-aead-4a0201be3817.png)

there is one place that I see reference to wire
![image](https://user-images.githubusercontent.com/47909923/177019084-adec3f0d-898d-4692-9870-979fea517957.png)

but wire isn't even included in the file?

**Comment by luni64** [comment]
What do you mean by "the others"`? According to your vsteensy.json you only use SPI and wire. The screenshot of your lib folder shows EEPROM, SPI and Time.  The screenshot of main.cpp shows that you want to a lot of other libraries. So, the 3 screenshots are kind of completely unrelated? 

Here a video showing how to set up libraries https://github.com/luni64/VisualTeensy/wiki/Using-Libraries. As long as you don't use libraries from the "Shared libraries" repository they will all end up in the lib folder.

**Comment by finncat62** [comment]
Yes, I've set up the libraries in visualTeensy in that section.
My question is this: 
where can I find the libraries included?
- The libraries from teensyduino and arduino libraries show up in the lib folder (photo project on the left, lib with eeprom, spi, time, on the right PWMServo, Wire).  However,
- libraries that have been added from the "installed, shared Libraries" section don't appear with the others. In the image on the left side there are libraries such as NewPing, Gfx, etc, which I don't see. Where I can find them? In the image on the right, they are under .vsteensy, build, lib. However, on the image on the left, .vsteensy => build is empty.
![image](https://user-images.githubusercontent.com/47909923/177054488-dd2b1f35-befb-4dea-9cc9-82f7bc35e923.png)
(Image shows two projects side by side, each with libraries from teensyduino and installed. One shows the installed libraries inside the .vsteensy => build  => lib, the other .vsteensy build is empty). 

(started a new project for photos of the process)
libraries added:
![image](https://user-images.githubusercontent.com/47909923/177054692-9449d00d-9c83-4253-a798-b23ccc3f9f08.png)

.vsteensy build empty, libraries not visable in main lib
![image](https://user-images.githubusercontent.com/47909923/177054749-b1785057-4c93-4e25-922b-7710fa23b780.png)

the goal is to go into the libraries and replace all references to the wire library with references to the replacement library, but I'm not seeing it.

Sidenote: I started both project folders the exact same way, why might they be different?

Thank you very much for the help and paitence,
~finncat62

**Comment by finncat62** [comment]
*another thing: I created a new project that only had wire included, not the teensy4_i2c. For some reason, it still shows up in the path, and I get an error saying multiple definitions of wire? What should I do? Wire and teensy4_i2c are exclusive, so having both at once creates issues, but I didn't include it and it's still making problems? 
![image](https://user-images.githubusercontent.com/47909923/177063144-24472d8d-1d10-4619-b2e6-a972188503f5.png)
![image](https://user-images.githubusercontent.com/47909923/177063207-628d805f-6ef0-4748-aed4-ac711b38c855.png)

**Comment by luni64** [comment]
Only libraries you select from the Teensyduino and the Arduino Repositories are copied to the project folder. Shared Libraries are used from the shared library folder. If you didn't change the configuration they should be under USERDIR\Documents\Arduino\libraries

I suggest to remove **all** the libraries from the shared library folder (shared libraries are a bad idea anyway) 
Then start a new project and include the libraries you need as shown in the video I linked. After saving the project they should be copied into your project/lib folder. As you know, there is no automatic library detection. Some libraries are dependent on other libraries, so you might need to add those libraries as well. Usually the compiler gives some very clear indications on which libraries it doesn't find. Also have a look (F12) into the headers with red wiggles.  It will show you which libraries are still missing. 

BTW Looking in the build folder is not very informative. This only shows the compilation results. The important files are the ones in .vsteensy/,  .vscode/ and the makefile.  If you can't get it compiling please zip the complete project and post here. I can then have a closer look

**Comment by luni64** [comment]
> *another thing: I created a new project that only had wire included, not the teensy4_i2c. For some reason, it still shows up in the path, and I get an error saying multiple definitions of wire? What should I do? Wire and teensy4_i2c are exclusive, so having both at once creates issues, but I didn't include it and it's still making problems?

By " I created a new project" you mean that you started with an empty project folder right?  

If opening a project VisualTeensy checks the /lib folder and automatically includes libraries it found there in the library folder. Also it never deletes code. So, if you start a new project in an existing folder  which already contains libraries you will have them in your project. Other than this I don't see any possibility how a library would sneak into your project.

**Comment by finncat62** [comment]
Cool. How do I change the file path here to the project library file: 
![image](https://user-images.githubusercontent.com/47909923/177207436-2411a501-e685-4397-99d0-ab560dee0c4a.png)

**Comment by luni64** [comment]
It reads it out from the Arduino preferences. In the Arduino IDE go to File|Preferences and change the Arduino Sketchbook folder to any convenient location.

**Comment by finncat62** [comment]
![image](https://user-images.githubusercontent.com/47909923/177388908-7d82d255-6867-4409-8c30-a9d31b0b92d6.png)

![image](https://user-images.githubusercontent.com/47909923/177388971-9eacf421-f917-4201-b441-f484783d9dde.png)

...?

**Comment by luni64** [comment]
Do you have a library folder in the new folder?

**Comment by finncat62** [comment]
perfect all good:)

to anyone seeing:
In arduino go to file => preferences, change the location to the place you want to have the new libraries. create a file called libraries and include everything inside, then visualTeensy will automatically change to search that when including :)

Thank you, sorry for the trouble.
