### ISSUE TITLE
concatenate multiple .ino files

### ISSUE THREAD

**Issue by jdavis-codes** [luni64/VisualTeensy#74]
I'm working with a pre-existing project, whose code is structured purposefully to work with the Ardunio IDE. There is a main loop .ino file, and several functions contained in their own .ino files. all are contained in the same src folder.

My understanding is that the arduino IDE concatenates all these files into one in the pre-processing step ([source](https://arduino.github.io/arduino-cli/0.21/sketch-build-process/#pre-processing)).

Is there any way to customize the make file that VisualTeensy creates to allow that same behavior? I've tried changing SKETCH_NAME to the name of the src folder with all .ino files, which did not work.

**Comment by luni64** [comment]
Did you try the Arduino Builder mode? 

![image](https://user-images.githubusercontent.com/12611497/177831732-64cf5a90-d748-44dc-9640-e8d91f4c1fd1.png)

This uses the Arduino builder and should give you the same results as with the Arduino IDE.

**Comment by jdavis-codes** [comment]
I figured out that if you edit the SKETCH_NAME to equal the direct path to a folder containing all the .ino files (C:\Users\name\Documents\sketch_folder) it will compile fine with arduino builder :) 

In the open and save project function, it might be nice functionality to be able to select a sketch folder and not just auto detect or create a single sketch file. But I could see how that would clash with opening a vanilla c++ project.
