### ISSUE TITLE
Error at startup of Release exe

### ISSUE THREAD

**Issue by elsucht** [luni64/VisualTeensy#9]
When i try to start a release .exe on my PC (Windows 10) i get the following error:
![visualteensy_bug](https://user-images.githubusercontent.com/46718391/51190270-268d9800-18e2-11e9-875d-4afc7c1ffdee.png)

**Comment by luni64** [comment]
Did you use the latest release 0.9.1 and follow this https://github.com/luni64/VisualTeensy/releases/tag/0.9.1  instructions?

If so, did you install Arduino & Teensyduino?

**Comment by elsucht** [comment]
using version 0.9.1 and following your instructions helped! Thanks a lot

**Comment by luni64** [comment]
Great, Let me know if you need further support
